name: balance_budget
description: Cross-platform app for budget planning and finance tracking
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  flutter_platform_widgets: ^3.2.0
  flutter_localizations:
    sdk: flutter
  intl: any
  async: ^2.10.0
  rxdart: ^0.27.7
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  firebase_ui_auth: ^1.2.0
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0
  firebase_ui_oauth_google: ^1.1.0
  flutter_launcher_icons: ^0.13.0
  calendar_date_picker2: ^0.5.1
  collection: ^1.17.0
  cloud_firestore: ^4.5.0
  flutter_iconpicker:
    git:
      url: https://github.com/kechankrisna/FlutterIconPicker
      ref: hotfix
  modal_bottom_sheet: ^3.0.0-pre
  ionicons: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  generate: true