name: balance_budget
description: Cross-platform app for budget planning and finance tracking
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  get: ^4.6.6
  flutter_platform_widgets: ^6.0.2
  flutter_localizations:
    sdk: flutter
#  intl: any
  async: ^2.10.0
  rxdart: ^0.27.7
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  firebase_ui_auth: ^1.10.0
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  firebase_ui_oauth_google: ^1.2.14
  flutter_launcher_icons: ^0.13.1
  calendar_date_picker2: ^0.5.3
  collection: ^1.17.2
  cloud_firestore: ^4.13.3
  flutter_iconpicker: ^3.2.4
  modal_bottom_sheet: ^3.0.0-pre
  ionicons: ^0.2.2
  csv: ^5.0.2
  file_picker: ^5.5.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  generate: true
flutter_intl:
  enabled: true