name: balance_budget
description: Cross-platform app for budget planning and finance tracking
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_platform_widgets: ^3.0.0
  flutter_localizations:
    sdk: flutter
  intl: any
  async: ^2.10.0
  rxdart: ^0.27.7
  firebase_core: ^2.5.0
  firebase_auth: ^4.2.6
  firebase_ui_auth: ^1.1.10
  firebase_database: ^10.0.10
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0
  firebase_ui_oauth_google: ^1.0.17
  flutter_timeline_calendar: ^1.0.3
  flutter_launcher_icons: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  generate: true