name: balance_budget
description: Cross-platform app for budget planning and finance tracking
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_platform_widgets: ^3.0.0
  flutter_localizations:
    sdk: flutter
  intl: any
  uuid: ^3.0.7
  async: ^2.10.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true